@DientesLimpios.API_HostAddress = https://localhost:7066/api/consultorios
@DientesLimpios.Token = CfDJ8DJuFDbh3StHjnqY0xYmNEJX9sVADsbRre46UZ58vHUjnTcZ0R7oY6CkB7Xi7q1uu5ZupUcPrqfh9lImzEuCOKxmxF2C9AqviBUIDRzll8cx9vcZ9P3WN-hzHv4e74iVeJgqXHUnxu5_ZJ8-yWh9CP_AuhQUV9vBMnF1lrU9MO1esj580748nzwl55H9XzwEj_zDLOFTnAA44kWsXbNumI3kxtimzXvjUNq5mbTKzW79rc_6Oyo9-lCD9fB_Iva0J23geMuIaibFMYHMFj2z6B4r3DidWfM8Oolt96j0d0oup14qLU2W1l0vY1Kmxpg8feZQBHN2TASjXEWY5q5ZUbUOMgW8bD3B527bea3KosFqKe2mDtRHIMnlA4vEfp1PTLXEb_w0kxpj8pJfLlAmXc7OwTJtQV9Fx1Y-9RdUQeAFRSPbUBj97zv9sv_tN_6ttof6roVq9soOtXjXg_UhS-tKXvRUIqZ_pIWAzCd0f8KKxEqyzowVlYMATNIfcLt2jmIAwAlEOvCt_on_k2fw7Ce8b4mfjN6Qubsj4cXTTpI_NFVyxkcQgX4PQj0CBsgJxhsFiRj9uklwMjh5VCDjvnS5jDFKEHyI_wvxopzP-6aWIk_vMVgGk52t5Qgo33G78GB6YCVhG-l7u3ZKH3cplws745ECyEHJLbtQFtRepbtIM6O7Pnkec4vcVH2bHWTTJ3b3kEjnAH-fcSw5yvvQw0M

GET {{DientesLimpios.API_HostAddress}}/0198F989-F9D3-77E9-91A4-00B0BDC32792
Accept: application/json

###

GET {{DientesLimpios.API_HostAddress}}?fechaInicio=2025-08-28T00:00:00&fechaFin=2026-08-28T00:00:00&dentistaId=0198f732-7614-739c-98f0-392cdffef316
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "pacienteId": "0198f26e-792d-73ce-b064-00d75f139455",
  "dentistaId": "0198f732-7614-739c-98f0-392cdffef316",
  "consultorioId": "0198ecce-bf0c-7d0f-beb6-59e4318ee9b3",
  "fechaInicio": "2025-09-01T12:30:00",
  "fechaFin": "2025-09-01T12:40:00"
}

###

POST {{DientesLimpios.API_HostAddress}}/0198F989-F9D3-77E9-91A4-00B0BDC32792/completar
Content-Type: application/json

###

POST {{DientesLimpios.API_HostAddress}}/0198FBCA-5434-73E9-9430-1B05A0A32C5B/cancelar
Content-Type: application/json