@DientesLimpios.API_HostAddress = https://localhost:7066/api/consultorios
@DientesLimpios.Token = CfDJ8DJuFDbh3StHjnqY0xYmNEJX9sVADsbRre46UZ58vHUjnTcZ0R7oY6CkB7Xi7q1uu5ZupUcPrqfh9lImzEuCOKxmxF2C9AqviBUIDRzll8cx9vcZ9P3WN-hzHv4e74iVeJgqXHUnxu5_ZJ8-yWh9CP_AuhQUV9vBMnF1lrU9MO1esj580748nzwl55H9XzwEj_zDLOFTnAA44kWsXbNumI3kxtimzXvjUNq5mbTKzW79rc_6Oyo9-lCD9fB_Iva0J23geMuIaibFMYHMFj2z6B4r3DidWfM8Oolt96j0d0oup14qLU2W1l0vY1Kmxpg8feZQBHN2TASjXEWY5q5ZUbUOMgW8bD3B527bea3KosFqKe2mDtRHIMnlA4vEfp1PTLXEb_w0kxpj8pJfLlAmXc7OwTJtQV9Fx1Y-9RdUQeAFRSPbUBj97zv9sv_tN_6ttof6roVq9soOtXjXg_UhS-tKXvRUIqZ_pIWAzCd0f8KKxEqyzowVlYMATNIfcLt2jmIAwAlEOvCt_on_k2fw7Ce8b4mfjN6Qubsj4cXTTpI_NFVyxkcQgX4PQj0CBsgJxhsFiRj9uklwMjh5VCDjvnS5jDFKEHyI_wvxopzP-6aWIk_vMVgGk52t5Qgo33G78GB6YCVhG-l7u3ZKH3cplws745ECyEHJLbtQFtRepbtIM6O7Pnkec4vcVH2bHWTTJ3b3kEjnAH-fcSw5yvvQw0M

GET {{DientesLimpios.API_HostAddress}}/0198ECCE-BF0C-7D0F-BEB6-59E4318EE9B3
Accept: application/json
Authorization: Bearer {{DientesLimpios.Token}}

###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer {{DientesLimpios.Token}}

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer {{DientesLimpios.Token}}

{
  "nombre" : "Consultorio C"
}

###

PUT {{DientesLimpios.API_HostAddress}}/0198fe57-f04a-75f8-a4d1-d92341577742
Content-Type: application/json
Authorization: Bearer {{DientesLimpios.Token}}

{
  "nombre" : "Consultorio C - Actualizado"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/0198eee5-d137-7ad4-bdd4-8c63fa3da2c7
Content-Type: application/json
Authorization: Bearer {{DientesLimpios.Token}}