@DientesLimpios.API_HostAddress = http://localhost:5100/api/dentistas

GET {{DientesLimpios.API_HostAddress}}/0198f732-7614-739c-98f0-392cdffef316
Accept: application/json

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre" : "Dentista C",
  "email" : "dentistaC@ejemplo.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/0198f951-571f-73d9-aeb2-84c52a133a8e
Content-Type: application/json

{
  "nombre" : "Dentista D - Actualizado",
   "email": "pacienteDactualizado@ejemplo.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/0198f732-8fc5-7d35-a2cb-5ba05c9e0885
Content-Type: application/json