@DientesLimpios.API_HostAddress = https://localhost:7066/api/consultorios
@DientesLimpios.Token = CfDJ8DJuFDbh3StHjnqY0xYmNEJX9sVADsbRre46UZ58vHUjnTcZ0R7oY6CkB7Xi7q1uu5ZupUcPrqfh9lImzEuCOKxmxF2C9AqviBUIDRzll8cx9vcZ9P3WN-hzHv4e74iVeJgqXHUnxu5_ZJ8-yWh9CP_AuhQUV9vBMnF1lrU9MO1esj580748nzwl55H9XzwEj_zDLOFTnAA44kWsXbNumI3kxtimzXvjUNq5mbTKzW79rc_6Oyo9-lCD9fB_Iva0J23geMuIaibFMYHMFj2z6B4r3DidWfM8Oolt96j0d0oup14qLU2W1l0vY1Kmxpg8feZQBHN2TASjXEWY5q5ZUbUOMgW8bD3B527bea3KosFqKe2mDtRHIMnlA4vEfp1PTLXEb_w0kxpj8pJfLlAmXc7OwTJtQV9Fx1Y-9RdUQeAFRSPbUBj97zv9sv_tN_6ttof6roVq9soOtXjXg_UhS-tKXvRUIqZ_pIWAzCd0f8KKxEqyzowVlYMATNIfcLt2jmIAwAlEOvCt_on_k2fw7Ce8b4mfjN6Qubsj4cXTTpI_NFVyxkcQgX4PQj0CBsgJxhsFiRj9uklwMjh5VCDjvnS5jDFKEHyI_wvxopzP-6aWIk_vMVgGk52t5Qgo33G78GB6YCVhG-l7u3ZKH3cplws745ECyEHJLbtQFtRepbtIM6O7Pnkec4vcVH2bHWTTJ3b3kEjnAH-fcSw5yvvQw0M

GET {{DientesLimpios.API_HostAddress}}/0198f732-7614-739c-98f0-392cdffef316
Accept: application/json

###

GET {{DientesLimpios.API_HostAddress}}?pagina=1&RegistrosPorPagina=10
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre" : "Dentista C",
  "email" : "dentistaC@ejemplo.com"
}

###

PUT {{DientesLimpios.API_HostAddress}}/0198f951-571f-73d9-aeb2-84c52a133a8e
Content-Type: application/json

{
  "nombre" : "Dentista D - Actualizado",
   "email": "pacienteDactualizado@ejemplo.com"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/0198f732-8fc5-7d35-a2cb-5ba05c9e0885
Content-Type: application/json